apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::983877353540:role/jenkins-eks-access-role
      username: jenkins
      groups:
        - system:masters
